### ISSUE TITLE
dev server infinite loop (never resolves)

### ISSUE THREAD

**Issue by tizmagik** [iam4x/isomorphic-flux-boilerplate#100] opened 2015-07-31 17:54 UTC
I get this after running `npm run dev`, continuously scrolling in the console:

```
koa blocked for 224ms +45ms
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997711-19734
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997734-19737
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997727-19736
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997725-19735
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997746-19739
  <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997741-19738
  dev locale of request: en +8ms
  dev locale of request: en +3ms
  dev locale of request: en +5ms
  dev locale of request: en +3ms
  dev locale of request: en +5ms
  dev locale of request: en +16ms
  dev first render +1ms
  dev first render +12ms
  dev first render +19ms
  dev first render +5ms
  dev first render +5ms
  dev first render +5ms
  dev second render +10ms
  dev second render +5ms
  dev second render +8ms
  dev second render +6ms
  dev second render +6ms
  dev second render +75ms
  dev return html content +29ms
  dev return html content +1ms
  dev return html content +0ms
  dev return html content +1ms
  dev return html content +0ms
  dev return html content +1ms
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997711-19734 200 231ms 4.38kb
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997734-19737 200 230ms 4.36kb
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997727-19736 200 230ms 4.38kb
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997725-19735 200 231ms 4.38kb
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997746-19739 200 273ms 4.36kb
  --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1438364997741-19738 200 272ms 4.38kb
  koa blocked for 178ms +50ms
...
```

**Comment by iam4x** [comment] 2015-08-03 18:02
On what OS are you @tizmagik ?

**Comment by tizmagik** [comment] 2015-08-03 19:42
Mac OS X 10.10.4 @iam4x

**Comment by elimence** [comment] 2015-10-08 17:54
did anyone figure out how to fix this?

**Comment by iam4x** [comment] 2015-10-15 22:48
@elimence No, could you give me more informations:

* nodejs version
* os version

I'll try to set up a VM with the same env.

**Comment by elimence** [comment] 2015-10-16 01:07
I'm using 
NodeJS v4.1.2
NPM 3.3.6
Max OSX El Capitan Version 10.11

**Comment by iam4x** [comment] 2015-10-16 20:57
@elimence I'm setting up a VM, could you give me your ENV? ` $ ENV | pbcopy`

**Comment by elimence** [comment] 2015-10-16 21:11
@iam4x 

NVM_RC_VERSION=
TERM_PROGRAM=iTerm.app
LESS_TERMCAP_md=[38;5;136m
TERM=xterm-256color
SHELL=/bin/bash
HISTSIZE=32768
TMPDIR=/var/folders/08/69n_ds8j13128jrpqg_f_mvh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.pFfQjz1plb/Render
LC_ALL=en_US.UTF-8
NVM_DIR=/Users/djones/.nvm
HISTFILESIZE=32768
USER=djones
LS_COLORS=no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:
COMMAND_MODE=unix2003
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/sbin:/Users/djones/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
EDITOR=vim
LANG=en_US.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PS1=\[\033]0;\w\007\]\[[1m\]\n\[[38;5;166m\]djones\[[97m\] at \[[38;5;136m\]\@\[[97m\] in \[[38;5;64m\]\w$(prompt_git "[97m on [38;5;61m")\n\[[97m\]$ \[(B[m\]
HISTIGNORE=ls:cd:cd -:pwd:exit:date:* --help
HISTCONTROL=ignoredups
PS2=\[[38;5;136m\]→ \[(B[m\]
XPC_SERVICE_NAME=0
MANPAGER=less -X
SHLVL=1
HOME=/Users/djones
COLORFGBG=7;0
GREP_OPTIONS=--color=auto
ITERM_SESSION_ID=w1t4p0
LOGNAME=djones
LC_CTYPE=UTF-8
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
DISPLAY=/private/tmp/com.apple.launchd.nmUUEg609M/org.macosforge.xquartz:0
SECURITYSESSIONID=186a6
_=/usr/bin/ENV

**Comment by iam4x** [comment] 2015-10-16 21:30
<img width="349" alt="screen shot 2015-10-16 at 23 26 31" src="https://cloud.githubusercontent.com/assets/893837/10553737/829c780a-745d-11e5-83e6-66c319b9119a.png">

I can't reproduce... Is this happening from new git clone of the boilerplate? Have you tried running on another port: `$ PORT=4000 npm run dev` ?

**Comment by elimence** [comment] 2015-10-16 21:35
Haven't tried that yet.
I'll get try with a different port, see how that goes.
Thanks

**Comment by iam4x** [comment] 2015-11-16 10:31
I'll close this since there's no more answers. Feel free to re-open with more details to re-produce.

**Closed by iam4x** 2015-11-16 10:31 UTC
Labels: bug
