### ISSUE TITLE
Issue with webpack 1.9.12

### ISSUE THREAD

**Issue by jonaswindey** [iam4x/isomorphic-flux-boilerplate#78] opened 2015-06-26 07:21 UTC
Edit: this issue is related to webpack: https://github.com/webpack/webpack/issues/1192

The project currently doesn't work. I get the following error with a vanilla installation:
```
http://10.0.0.3:3001/assets/4-aa0fe71ef222f5402be3.js Failed to load resource: the server responded with a status of 404 (Not found)
```
The main app (http://10.0.0.3:3001/assets/app-8567143c47916587f5e1d152bf4d05fe.js) is loading currectly, but it fails to load the chunk to continue.

NodeJS v0.12.4

**Comment by jonaswindey** [comment] 2015-06-26 07:40
Also, the stylesheets don't load, but I guess that's normal since the head chunk isn't loaded.

**Comment by jonaswindey** [comment] 2015-06-26 07:59
When I look at what's webpack is generating:
``` 
app-0bd847614be205bafbf05373870af9c3.js  4.88 MB       0  [emitted]  app
  1-453b2687f99276187e87ec26d03e88fc.js   381 kB    1, 3  [emitted]  
  2-f19441f78ad604ad2843358e8955a382.js   376 kB    2, 4  [emitted]  
  3-0a08dafb4a602ece0bf24d0d208e5d94.js  3.64 kB       3  [emitted]  
  4-83fc841ec3d30afd41fe80f3372292ff.js  3.59 kB       4  [emitted]  
``` 
It seems to load 4-aa0fe71ef222f5402be3.js instead of 4-83fc841ec3d30afd41fe80f3372292ff.js

**Comment by jonaswindey** [comment] 2015-06-26 08:38
I have found a solution, I think it's related to webpack 1.9.12 (since we load ^1.9.11 it takes the .12 with a clean install)

I committed a pull request.

**Comment by iam4x** [comment] 2015-06-26 11:21
Hello @jonaswindey I would prefer to fix webpack to `=1.9.11` until the issue is fixed into webpack.

Nice catch anyway, I'll close your PR and change the webpack version.

**Closed** 2015-06-26 11:24 UTC

**Comment by jonaswindey** [comment] 2015-06-26 13:06
Are you sure you pushed your update? 
I still see `"webpack": "^1.9.11" ` in package.json

**Comment by iam4x** [comment] 2015-06-26 13:56
Yes sorry, now it's good.
